### ISSUE TITLE
Creator as "undefined undefined" in new data entries (climate and 

### ISSUE THREAD

**Issue by hoganwr** [midas-isg/digital-commons#122]

**Comment by hoganwr** [comment]
I think the reason is that the attribute nested under "creators" is specified in the new entries as "name", whereas the old entries all use "firstName", "lastName", and "email".  So your display code is probably not recognizing the newly introduced "name" attribute.

**Comment by JohnLevander** [comment]
This is an old bug that I believe I fixed long ago (creator is now showing under climate).  Feel free to re-open if you think that it's still not fixed.
