### ISSUE TITLE
Identifiers for "2014, Mali Ebola epidemic data" and "2014, Democratic Republic of Congo Ebola epidemic data" are the same

### ISSUE THREAD

**Issue by dillerm** [midas-isg/digital-commons#124]
Mali's identifier should be 'https://doi.org/10.5281/zenodo.572259'.

**Comment by JohnLevander** [comment]
Sahawut is working on this.  It should be a quick fix.

**Comment by sahawut** [comment]
Should be resolved on dev version:
Corrected the identifier of "2014, Mali Ebola epidemic data" to be "https://doi.org/10.5281/zenodo.572259".

**Comment by dillerm** [comment]
Looks good, thanks guys.
