### ISSUE TITLE
Tycho datasets' descriptions contain newline characters

### ISSUE THREAD

**Issue by dillerm** [midas-isg/digital-commons#134]

**Comment by JohnLevander** [comment]
Is this a bug?  I was thinking about it...how are you supposed to indicate a new line / line break in JSON?

**Comment by dillerm** [comment]
I didn't see any reason for why it was there since the code for the pop-ups seems to ignore them. I can always just have my code ignore it too if you think that it would be better to keep them there.

**Comment by jeffstazer** [comment]
Line breaks should now appear in the HTML.
