### ISSUE TITLE
MIDAS-ISG:WS-000080 and MIDAS-ISG:WS-000081 both seem to overlap

### ISSUE THREAD

**Issue by dillerm** [midas-isg/digital-commons#135]
Both are disease surveillance datasets for the Cayman Islands. The [link](https://www.hsa.ky/ShowContent.aspx?ID=250&Page=CommunicableDiseaseSurveillancereport) to the first seems to be the [landing page](https://www.hsa.ky/ContentFiles/Communicable%20Disease%20Surveillance%20Report%202014%20Amended%20(1).pdf) of the second.

**Comment by JohnLevander** [comment]
Let's delete 81.

Add an access URL of: https://www.hsa.ky/ContentFiles/Communicable%20Disease%20Surveillance%20Report%202014%20Amended%20(1).pdf

**Comment by jeffstazer** [comment]
These have been updated.
