### ISSUE TITLE
Landing page for MIDAS-ISG:WS-000098 doesn't exist

### ISSUE THREAD

**Issue by dillerm** [midas-isg/digital-commons#137]
I would have tried to find the correct page, but my Spanish is a bit rusty.

**Comment by jeffstazer** [comment]
Updating the link from...
http://www.ins.gov.co/boletin-epidemiologico/Paginas/default.aspx
to...
http://www.ins.gov.co/buscador-eventos/Paginas/Vista-Boletin-Epidemilogico.aspx

**Comment by dillerm** [comment]
I think someone added the website mentioned in @JohnLevander's comment from #135 as an access page for this dataset. The landing page, however, has been corrected.

**Comment by jeffstazer** [comment]
There is something strange happening where the Access URL is persisting in the HTML view of a separate entry when no Access URL has been specified. If an Access URL has not been entered this line item shouldn't appear.  Creating a new ticket for this issue.
