### ISSUE TITLE
Was not able to pull up data on disease incidence for MIDAS-ISG:WS-000036 (Bahrain)

### ISSUE THREAD

**Issue by dillerm** [midas-isg/digital-commons#139]
May want to remove this one. Tried playing around with it a bit to find out what diseases it covers, but it doesn't look like the dataset contains anything about disease incidence.

**Comment by JohnLevander** [comment]
I've alerted the submitter and I am awaiting feedback

**Comment by JohnLevander** [comment]
Okay the data is there.  Select Indicators->1.4 Health->Incidences of Notifiable Communicable Diseases.  It doesn't look like we can automatically open that section by tweaking the URL, so we just have to leave it as it is in my opinion. Please close this if you are agree.

![image](https://user-images.githubusercontent.com/11561825/37675640-1eac2ae4-2c4c-11e8-8611-03229b99e116.png)

**Comment by dillerm** [comment]
I was able to find it this time. Thanks for the follow-up.

**Comment by dillerm** [comment]
Just took a second look, and I just realized that the data itself doesn't seem to be there even though the indicators are. See below (note: I selected every disease indicator for communicable diseases and every year, and all the rows are blank):

<img width="1361" alt="screen shot 2018-03-20 at 3 35 51 pm" src="https://user-images.githubusercontent.com/11520343/37678457-802d86fc-2c54-11e8-8d17-bfe9eb5e697f.png">

**Comment by JohnLevander** [comment]
This is a website with data now.
