### ISSUE TITLE
Landing page for MIDAS-ISG:WS-000138 returns 404 error

### ISSUE THREAD

**Issue by dillerm** [midas-isg/digital-commons#141]
Tried going to the [homepage](ncdc.ge) of the website and looking for the dataset from there, but had no luck. None of the web pages that were related to disease surveillance or communicable diseases even contained information.  Dataset can be found in MDC under Datasets > Disease surveillance data > Asia > Georgia.

**Comment by dillerm** [comment]
I just realized that the reason I couldn't see anything is because I was looking at the English version of the website. Only the Arabic version displays the links to datasets. Unfortunately, all of the information in the datasets seem to be in Arabic.

**Comment by JohnLevander** [comment]
I will email the submitter and see what the new URL should be...

**Comment by JohnLevander** [comment]
The data has been deleted.  Jeff please remove this entry (WS-000138) from the MDC.

**Comment by jeffstazer** [comment]
WS-000138 entry has been removed.
