### ISSUE TITLE
MIDAS-ISG:WS-000246 doesn't provide any information on what is suggested

### ISSUE THREAD

**Issue by dillerm** [midas-isg/digital-commons#142]
Not an issue on our end, but rather on whoever created the website and/or dataset. The data doesn't provide any information on the types of immunizations or communicable diseases that are covered by the data, and is therefore useless. I recommend removing it.

Can be found in Datasets > Disease surveillance data > Asia > Mongolia > "Vaccination Coverage and Incidences of Infectious Diseases of the Mongolian Statistical Information Service"

**Comment by dillerm** [comment]
MIDAS-ISG:WS-000248 is also a duplicate of this. Not sure if you want me to create a separate issue for this or not.

**Comment by JohnLevander** [comment]
Jeff please hide (is_public = false) WS-000246 and make WS-000248 a "Website with Data [in Asia]"  FYI "Websites with data" is the last category in the Data column.

**Comment by jeffstazer** [comment]
MIDAS-ISG:WS-000246 will no longer be public.

MIDAS-ISG:WS-000248 will now appear in the "Website with Data [in Asia]" section.

These updates will need published.
