### ISSUE TITLE
MIDAS-ISG:WS-000346 doesn't really add value to the MDC

### ISSUE THREAD

**Issue by dillerm** [midas-isg/digital-commons#144]
The weekly report on Ebola is more relevant to other countries since Oman never had any cases. I would recommend either removing from the MDC altogether or placing this dataset elsewhere.

Can be found at Datasets > Disease surveillance data > Asia > Oman

**Comment by JohnLevander** [comment]
I think we should keep it, because it is a report that contains information about Oman, hosted by the government of Oman.  Even if Oman didn't have any cases, I still think that someone looking for disease data about Oman would find it useful.  Do you have a strong opinion about removing it?

**Comment by dillerm** [comment]
My only objections would be that most people using the MDC probably would be aware that Oman has never seen a case of Ebola since it's something that only a small amount of countries have experienced an outbreak of, and that we generally try to avoid creating ontology classes or individuals for things that don't exist (i.e., 'population of Ebola virus in Oman').

**Comment by dillerm** [comment]
Discussed this in person with @hoganwr , and we agreed that it should not be removed.
