### ISSUE TITLE
MIDAS-ISG:WS-000419 has 'Japanese encephalitis' listed twice in 'isAbout' JSON array

### ISSUE THREAD

**Issue by dillerm** [midas-isg/digital-commons#145]
Can be found in MDC under Datasets > Disease surveillance data > Asia > South Korea > "Surveillance Data of the National Infectious Disease Surveillance System (NIDSS) of South Korea, 2001-2017"

**Comment by JohnLevander** [comment]
Jeff please remove one instance of Japanese encephalitis from the JSON.

**Comment by jeffstazer** [comment]
Removed 2nd entry of Japanese encephalitis.
