### ISSUE TITLE
Landing page of MIDAS-ISG:WS-000043 does not take you to the mentioned datasets, and is entirely in Russian

### ISSUE THREAD

**Issue by dillerm** [midas-isg/digital-commons#146]
Landing page should probably be this: http://www.belstat.gov.by/en/ofitsialnaya-statistika/social-sector/zdravoohranenie_2/godovye-dannye-1995-2011-gody/main-indicators-of-public-health/

**Comment by dillerm** [comment]
May also want to replace 'Scabies' in the isAbout JSON array with 'HIV'

**Comment by JohnLevander** [comment]
Jeff please update the landing page to the link that Matt suggested for WS-000043.  Then in the JSON, replace the Scabies entry with "Human immunodeficiency virus" (identifier:12721).  Then delete WS-000044.

**Comment by jeffstazer** [comment]
For: MIDAS-ISG:WS-000043
Updated Landing page ; replaced Scabies with "Human immunodeficiency virus" and updated identifier to 12721

MIDAS-ISG:WS-000044 will no longer appear after updates are Published.
