### ISSUE TITLE
Update landing page for WS-000139 

### ISSUE THREAD

**Issue by JohnLevander** [midas-isg/digital-commons#147]
Update the link (now returning a 404), to:

http://ncdc.ge/Pages/User/Documents.aspx?ID=f2170773-a494-43d0-97fd-bfb0a06a6aa6

**Comment by jeffstazer** [comment]
Updated Landing Page to [http://ncdc.ge/Pages/User/Documents.aspx?ID=f2170773-a494-43d0-97fd-bfb0a06a6aa6](http://ncdc.ge/Pages/User/Documents.aspx?ID=f2170773-a494-43d0-97fd-bfb0a06a6aa6)
