### ISSUE TITLE
MIDAS-ISG:WS-000366 doesn't seem to be available at the moment (Poland)

### ISSUE THREAD

**Issue by dillerm** [midas-isg/digital-commons#148]
[Landing page](http://www.pzh.gov.pl/en/epidemiological-reports/) currently says "Site under construction." None of the datasets mentioned in the description are available.

**Comment by JohnLevander** [comment]
Jeff, please update the landing page to: http://www.pzh.gov.pl/meldunki-epidemiologiczne/

**Comment by dillerm** [comment]
Looks good! Was able to find everything there. Thanks guys.
