### ISSUE TITLE
Visiting the ontology search from betaweb results in an error.

### ISSUE THREAD

**Issue by JohnLevander** [midas-isg/digital-commons#149]
If I load https://betaweb.rods.pitt.edu/digital-commons-dev, click Search->Ontology-based search, the search page loads, but I get the following errors in the javascript console:

> 502 Bad Gateway
> mdcsearchdev.onbc.io/#/:1 Failed to load http://devapi.onbc.io/mdc_retrieval: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://mdcsearchdev.onbc.io' is therefore not allowed access. The response had HTTP status code 502.

Obviously, at this point I can't select pathogens, etc.

Should I be hitting another URL?

**Comment by dillerm** [comment]
@atloiaco may be able to provide more insight on this than I can.

**Comment by jeffstazer** [comment]
It seems the site must have been down when John tried to access it.  I've tested the search page successfully multiple times over the last few days.
