### ISSUE TITLE
Landing page for MIDAS-ISG:WS-000330 includes links to three other datasets in MDC

### ISSUE THREAD

**Issue by dillerm** [midas-isg/digital-commons#150]
Title of dataset is "Annual Reports on Notifiable Infectious Diseases of the New Zealand Public Health Surveillance, 2013-2016."

MIDAS-ISG:WS-000333 is the 2013 dataset
MIDAS-ISG:WS-000332 is the 2014 dataset
MIDAS-ISG:WS-000331 is the 2015 dataset

Links to the above three are to the PDF download itself, rather than any particular web page. Since  the same diseases are included in each from year to year, it might be better to just consolidate into one entry on the MDC.

**Comment by JohnLevander** [comment]
This is a website with data now.  Anything that is a website with data will be scrutinized when if/when it moves back to the data column
