### ISSUE TITLE
MIDAS-ISG:WS-000159 only covers chronic non-infectious diseases

### ISSUE THREAD

**Issue by dillerm** [midas-isg/digital-commons#152]
Dataset is titled "Leading Causes of Death in Guyana, 2000-2009" and is under "Mortality data."

**Comment by jeffstazer** [comment]
Should this be removed from the MDC or edited to something more apt?

**Comment by dillerm** [comment]
I'm thinking we may want to remove it, unless anyone sees a reason for why it should be there.

**Comment by JohnLevander** [comment]
This is a website with data now.
