### ISSUE TITLE
Website for MIDAS-ISG:WS-000397 doesn't contain the data that the description in MDC suggests it does

### ISSUE THREAD

**Issue by dillerm** [midas-isg/digital-commons#154]
Description says that the website contains datasets on vaccination coverage for several years, but the website only contains annual epidemiological reports, among other less relevant things. None of these contained data on vaccination coverage.

Website: http://www.health.gov.sc/index.php/reports/

**Comment by jeffstazer** [comment]
Disease surveillance data > Africa > Seychelles
Full Description: "This website with data contains data about vital statistics, causes of deaths, immunization, morbidity in Seychelles from 2016 to 2017 year in PDF format. Spatial coverage is country, and spatial resolution is country. Temporal coverage is 2016-2017, and temporal resolution is monthly. Open access."

Should this entry be removed or edited to something more apt?

**Comment by dillerm** [comment]
I think it would be worthwhile to keep it and just edit the description, unless we can find out what happened to the original datasets.

**Comment by JohnLevander** [comment]
This is moved to websites with data.
