### ISSUE TITLE
MIDAS-ISG:WS-000468 only contains data on non-infectious diseases

### ISSUE THREAD

**Issue by dillerm** [midas-isg/digital-commons#157]
Website contains a table on the incidence of non-infectious diseases over a 25-year period. There is nothing in here about infectious diseases, particularly.

Location: Datasets > Website with Data > Europe > "Morbidity Data by ICD of the National Statistical Committee of the Republic of Ukraine, 1990-2015"

**Comment by JohnLevander** [comment]
It's under websites with data now.
