### ISSUE TITLE
Website for MIDAS-ISG:WS-000353 does not contain data suggested in the description

### ISSUE THREAD

**Issue by dillerm** [midas-isg/digital-commons#160]
Description: 

> This website with data contains annual report or health report can be requested through the online form or by calling.

URL: http://www.health.gov.pg/pages/sitemap.htm 

Location: Datasets > Websites with data > Oceania > "Papua New Guinea National Department of Health"

**Comment by dillerm** [comment]
I looked around on the website for the reports, but had no luck finding them.

**Comment by jeffstazer** [comment]
I am guessing you looked at these, but just double checking...
Are these National Department Of Health Sector Performance Annual Review helpful?

[http://www.health.gov.pg/pages/healthpolicyA.htm](url)

**Comment by dillerm** [comment]
No, I hadn't seen those actually. Perhaps we should change the landing page to the URL in your above comment.

**Comment by jeffstazer** [comment]
The landing page has been updated to...

[http://www.health.gov.pg/pages/healthpolicyA.htm](http://www.health.gov.pg/pages/healthpolicyA.htm)
