### ISSUE TITLE
Landing page for MIDAS-ISG:WS-000427 doesn't open

### ISSUE THREAD

**Issue by dillerm** [midas-isg/digital-commons#161]
Location: Datasets > Disease surveillance data > Africa > Sudan > "Annual Statistical Reports on Infectious Diseases of the Sudan Health Observatory, 1990-2015"

**Comment by jeffstazer** [comment]
The root of the URL isn't bringing anything up either.  I suspect it's a dead site, but let me check it again next week and if it's still not coming up, I'll remove it.

**Comment by JohnLevander** [comment]
This is a website with data now.
