### ISSUE TITLE
Not sure if MIDAS-ISG:WS-000513 is related to infectious disease surveillance

### ISSUE THREAD

**Issue by dillerm** [midas-isg/digital-commons#163]
For that matter, I don't even know if it even has any data on infectious diseases. I couldn't find any online documentation for it, and none of the articles about it made any mention of infectious diseases.

Location: Datasets > Disease surveillance data > Americas > Venezuela > "Automated Health Control and Surveillance System"

**Comment by JohnLevander** [comment]
This is moved to websites with data.
