### ISSUE TITLE
Dataset creation date denoted by two different values

### ISSUE THREAD

**Issue by dillerm** [midas-isg/digital-commons#165]
In the Project Tycho datasets, it's labeled as 'created', whereas in all others it's 'creation'.

**Comment by JohnLevander** [comment]
We need to change all instances of "created" to "creation."

We want this:
               "date":"2017-01-19",
               "type":{  
                  "value":"created",
                  "valueIRI":"http://purl.obolibrary.org/obo/GENEPIO_0001882"
               }

to look like this

               "date":"2017-01-19",
               "type":{  
                  "value":"creation",
                  "valueIRI":"http://purl.obolibrary.org/obo/GENEPIO_0001882"
               }


here is the where clause 

 where entry.content->>'entry'::text like '%\"created\"%'

**Comment by jeffstazer** [comment]
created has been replaced with creation for all value properties.
