### ISSUE TITLE
Index CAFE project

### ISSUE THREAD

**Issue by espinoj** [midas-isg/digital-commons#167]
https://github.com/younglululu/CAFE/releases/tag/1.0.0
10.5281/zenodo.1216178

**Comment by espinoj** [comment]
Still not seeing update button

**Comment by jeffstazer** [comment]
The button is on [dev](http://betaweb.rods.pitt.edu/digital-commons-dev/add/review
)

**Comment by espinoj** [comment]
Ok.  Should I make the entry on dev, publish then notify the USC guys that it will show up when we sync to prod?

**Comment by jeffstazer** [comment]
John is pushing the updates, please hold

**Comment by JohnLevander** [comment]
Since it looks like we are adding categories...is this something you want in an existing category or a new one?

**Comment by espinoj** [comment]
See #178

**Comment by JohnLevander** [comment]
This has been indexed.
