### ISSUE TITLE
None of the data formats listed in the Omnivore v0.5 are listed in the Data Formats section of MDC

### ISSUE THREAD

**Issue by hoganwr** [midas-isg/digital-commons#168]
Input formats
MIDAS-ISG:epidemiological-bulletin-national-system-of-epidemiological-surveillance-system-v1.0
MIDAS-ISG:number-reported-cases-of-chikungunya-fever-in-the-americas-v1.0
MIDAS-ISG:colombia-moh-chikungunya-weekly-summary-v1.0
MIDAS-ISG:colombia-municipal-routine-surveillance-events-by-week-v1.0

None of these input formats show up in MDC under the Data Formats section.

Output format
MIDAS-ISG:omnivore-v0.5 

The MDC does have MIDAS-ISG:omnivore-output-format-v2.0 but not version 0.5.  How different are these?

**Comment by JohnLevander** [comment]
I will have these added tomorrow.

**Comment by JohnLevander** [comment]
A added these formats.  They should be available on dev.

There is only one omnivore output format.  The format name has been set to MIDAS-ISG:omnivore-output-format-v2.0 in the software metadata.

I'm assuming @dillerm should be made aware of this so I am mentioning him now.
