### ISSUE TITLE
OAI-PMH support for deletions

### ISSUE THREAD

**Issue by jeffstazer** [midas-isg/digital-commons#170]
[2.5.1 Deleted records](http://www.openarchives.org/OAI/2.0/openarchivesprotocol.htm#deletion)
Dependent on the repository support for deletions.

If a record is no longer available then it is said to be deleted. Repositories must declare one of three levels of support for deleted records in the deletedRecord element of the Identify response:
	• no - the repository does not maintain information about deletions. A repository that indicates this level of support must not reveal a deleted status in any response.
	• persistent - the repository maintains information about deletions with no time limit. A repository that indicates this level of support must persistently keep track of the full history of deletions and consistently reveal the status of a deleted record over time.
	• transient - the repository does not guarantee that a list of deletions is maintained persistently or consistently. A repository that indicates this level of support may reveal a deleted status for records.

Which level do we want?

**Comment by JohnLevander** [comment]
We should not support deletions for now.  As long as it's okay for @espinoj.

**Comment by espinoj** [comment]
agreed no deletions for now (unless we do a protected endpoint.)
