### ISSUE TITLE
Dublin Core elements we don't appear to use

### ISSUE THREAD

**Issue by jeffstazer** [midas-isg/digital-commons#174]
[Dublin Core Elements](http://www.dublincore.org/documents/dces/)

From my search through the database and examining specific records we do not appear to use the following the elements...

rights
relation
contributor -- appears we overload the owner
language

These elements are not required, but please let me know if you feel they do map to an element in our records and should be included.

**Comment by JohnLevander** [comment]
Rights would be "license".

**Comment by jeffstazer** [comment]
Updated the oai-pmh web service for Rights information to be included with the Dublin Core elements.
