### ISSUE TITLE
Update MIDAS-ISG:WS-000495: Tuberculosis Data of the U.S. Department of Health, 2015

### ISSUE THREAD

**Issue by JohnLevander** [midas-isg/digital-commons#177]
Identifier should be: https://data.cdc.gov/api/views/ei7y-3g6s
Description: This Table includes total number of cases reported in the United States, by region and by states, in accordance with the current method of displaying MMWR data.  Data on United States will exclude counts from US territories.  
Extra properties: none
Creator: Centers for Disease Control and Prevention

Distributions should look like this:
"distributions": [
		{
			"size": 19.7,
			"unit": {
				"value": "kilobyte",
				"valueIRI": "http://purl.obolibrary.org/obo/UO_0000234"
			},
			"dates": [
				{
					"date": "2016-05-07",
					"type": {
						"value": "created",
						"valueIRI": "http://doi.org/10.5438/0012"
					}
				}
			],
			"title": "CSV",
			"access": {
				"types": [
					{
						"value": "download"
					}
				],
				"accessURL": "https://data.cdc.gov/api/views/ei7y-3g6s/rows.csv?accessType=DOWNLOAD",
				"identifier": {
					"identifier": "https://www.tycho.pitt.edu/data",
					"identifierSource": "URL"
				},
				"landingPage": "https://catalog.data.gov/dataset/nndss-table-iv-tuberculosis-83da5/resource/4a8d96a9-e818-4c12-b8cb-1680c465f14f"
			},
			"formats": [
				"CSV"
			],
			"version": "b2567110-9be7-4ca6-b48b-ec8f76c32de8",
			"licenses": [
				{
					"name": "Open Database License (ODbL)",
					"version": "1.0",
					"creators": [
						{
							"name": "Advisory Council for Open Data Commons",
							"identifier": {
								"identifier": "https://opendatacommons.org/about/advisory-council/",
								"identifierSource": "URL"
							},
							"abbreviation": "ODbL"
						}
					],
					"identifier": {
						"identifier": "http://opendefinition.org/licenses/odc-odbl/",
						"identifierSource": "URL"
					}
				}
			],
			
			"description": "Downloadable CSV"
		},
		{
			"size": 286,
			"unit": {
				"value": "kilobyte",
				"valueIRI": "http://purl.obolibrary.org/obo/UO_0000234"
			},
			"dates": [
				{
					"date": "2016-05-07",
					"type": {
						"value": "created",
						"valueIRI": "http://doi.org/10.5438/0012"
					}
				}
			],
			"title": "RDF",
			"access": {
				"types": [
					{
						"value": "download"
					}
				],
				"accessURL": "https://data.cdc.gov/api/views/ei7y-3g6s/rows.rdf?accessType=DOWNLOAD",
				"identifier": {
					"identifier": "https://www.tycho.pitt.edu/data",
					"identifierSource": "URL"
				},
				"landingPage": "https://catalog.data.gov/dataset/nndss-table-iv-tuberculosis-83da5/resource/c3a73573-b908-40d0-bac2-81f1b55cb03a"
			},
			"formats": [
				"RDF"
			],
			"version": "b2567110-9be7-4ca6-b48b-ec8f76c32de8",
			"licenses": [
				{
					"name": "Open Database License (ODbL)",
					"version": "1.0",
					"creators": [
						{
							"name": "Advisory Council for Open Data Commons",
							"identifier": {
								"identifier": "https://opendatacommons.org/about/advisory-council/",
								"identifierSource": "URL"
							},
							"abbreviation": "ODbL"
						}
					],
					"identifier": {
						"identifier": "http://opendefinition.org/licenses/odc-odbl/",
						"identifierSource": "URL"
					}
				}
			],
			
			"description": "Downloadable RDF"
		},
		{
			"size": 118,
			"unit": {
				"value": "kilobyte",
				"valueIRI": "http://purl.obolibrary.org/obo/UO_0000234"
			},
			"dates": [
				{
					"date": "2016-05-07",
					"type": {
						"value": "created",
						"valueIRI": "http://doi.org/10.5438/0012"
					}
				}
			],
			"title": "JSON",
			"access": {
				"types": [
					{
						"value": "download"
					}
				],
				"accessURL": "https://data.cdc.gov/api/views/ei7y-3g6s/rows.json?accessType=DOWNLOAD",
				"identifier": {
					"identifier": "https://www.tycho.pitt.edu/data",
					"identifierSource": "URL"
				},
				"landingPage": "https://catalog.data.gov/dataset/nndss-table-iv-tuberculosis-83da5/resource/4c8ff9cc-85e2-4998-b37f-7e74389e06ad"
			},
			"formats": [
				"JSON"
			],
			"version": "b2567110-9be7-4ca6-b48b-ec8f76c32de8",
			"licenses": [
				{
					"name": "Open Database License (ODbL)",
					"version": "1.0",
					"creators": [
						{
							"name": "Advisory Council for Open Data Commons",
							"identifier": {
								"identifier": "https://opendatacommons.org/about/advisory-council/",
								"identifierSource": "URL"
							},
							"abbreviation": "ODbL"
						}
					],
					"identifier": {
						"identifier": "http://opendefinition.org/licenses/odc-odbl/",
						"identifierSource": "URL"
					}
				}
			],
			
			"description": "JSON"
		},
		{
			"size": 205,
			"unit": {
				"value": "kilobyte",
				"valueIRI": "http://purl.obolibrary.org/obo/UO_0000234"
			},
			"dates": [
				{
					"date": "2016-05-07",
					"type": {
						"value": "created",
						"valueIRI": "http://doi.org/10.5438/0012"
					}
				}
			],
			"title": "XML",
			"access": {
				"types": [
					{
						"value": "download"
					}
				],
				"accessURL": "https://data.cdc.gov/api/views/ei7y-3g6s/rows.xml?accessType=DOWNLOAD",
				"identifier": {
					"identifier": "https://www.tycho.pitt.edu/data",
					"identifierSource": "URL"
				},
				"landingPage": "https://catalog.data.gov/dataset/nndss-table-iv-tuberculosis-83da5/resource/85a2e8d0-cd0e-49bc-b805-fc415bbe6a99"
			},
			"formats": [
				"XML"
			],
			"version": "b2567110-9be7-4ca6-b48b-ec8f76c32de8",
			"licenses": [
				{
					"name": "Open Database License (ODbL)",
					"version": "1.0",
					"creators": [
						{
							"name": "Advisory Council for Open Data Commons",
							"identifier": {
								"identifier": "https://opendatacommons.org/about/advisory-council/",
								"identifierSource": "URL"
							},
							"abbreviation": "ODbL"
						}
					],
					"identifier": {
						"identifier": "http://opendefinition.org/licenses/odc-odbl/",
						"identifierSource": "URL"
					}
				}
			],
			
			"description": "XML"
		},

	],

**Comment by jeffstazer** [comment]
for this identifier (https://data.cdc.gov/api/views/ei7y-3g6s) the source should be CDC, correct?

**Comment by jeffstazer** [comment]
This entry was revised in our harvest from data.gov.
