### ISSUE TITLE
Need to add type to every object added from the data.gov import

### ISSUE THREAD

**Issue by JohnLevander** [midas-isg/digital-commons#187]
for every "Disease surveillance data" dataset that we just imported from data.gov we need to add the following top level property:

"types": [
        {
            "method": {
                "value": "Disease Surveillance",
                "valueIRI": "http://purl.obolibrary.org/obo/APOLLO_SV_00000545"
            },
            "information": {
                "value": "Infectious disease incidence",
                "valueIRI": "http://purl.obolibrary.org/obo/IDO_0000479"
            }
        }
    ],

**Comment by jeffstazer** [comment]
Disease surveillance datasets for the new data.gov entries have been updated to include the "types" information indicated above.
