### ISSUE TITLE
Need to change IRI for the "created/creation" dates on Project Tycho datasets

### ISSUE THREAD

**Issue by JohnLevander** [midas-isg/digital-commons#190]
We need to change the valueIRI from: http://doi.org/10.5438/0012 to http://purl.obolibrary.org/obo/GENEPIO_0001882

where is the where clause (**be careful not to replace ALL instances of http://doi.org/10.5438/0012**).

select * from entry where entry.content->>'entry'::text like '%\"value": \"created\", \"valueIRI\": \"http://doi.org/10.5438/0012"%'

You may need to change "created" to "creation" in depending on when you get to this bug.

**Comment by jeffstazer** [comment]
The valueIRI has been updated for dates.

**Comment by jeffstazer** [comment]
And, created has been replaced with creation for all value properties.
