### ISSUE TITLE
On add entry page, "Spatial Coverage" section has inconsistent behavior 

### ISSUE THREAD

**Issue by JohnLevander** [midas-isg/digital-commons#193]
In Spatial Coverage, "Name" is available (you don't need to press +Add Name) by default, however Description is not.

Neither are required fields, and they are both just strings, so I don't know why one has behavior different from the other.

**Comment by JohnLevander** [comment]
Spatial Coverage should be from the place_schema, but it is currently built off the Biological Entity Schema.

Place Schema:

https://github.com/biocaddie/WG3-MetadataSpecifications/blob/master/json-schemas/place_schema.json

**Comment by jeffstazer** [comment]
Fixed in dats.xsd updates.
