### ISSUE TITLE
Spatial Coverage -- alternateIdentifiers did not populate

### ISSUE THREAD

**Issue by jeffstazer** [midas-isg/digital-commons#197]
spatialCoverage -> alternateIdentifiers is not initially populated even though contained in dataset
[http://localhost:8080/digital-commons/detailed-metadata-view/?id=2](http://localhost:8080/digital-commons/detailed-metadata-view/?id=2)
[http://localhost:8080/digital-commons/test-add-entry?entryId=2](http://localhost:8080/digital-commons/test-add-entry?entryId=2)
or
[http://localhost:8080/digital-commons/detailed-metadata-view/?id=1066](http://localhost:8080/digital-commons/detailed-metadata-view/?id=1066)
[http://localhost:8080/digital-commons/test-add-entry?entryId=1066](http://localhost:8080/digital-commons/test-add-entry?entryId=1066)

**Comment by JohnLevander** [comment]
Is this fixed?
