### ISSUE TITLE
Data Visualizers missing required fields in database json

### ISSUE THREAD

**Issue by JohnLevander** [midas-isg/digital-commons#202]
Entry "Galapagos" (625) needs 
	availableOnUIDS: false
	availableOnOlympus: false

Entry "Synthetic Microdata Household Viewer" (626) needs 
	availableOnUIDS: false
	availableOnOlympus: false
	signInRequired: false

Entry "Apollo Library Viewer" (621) needs 
	availableOnOlympus: false 
	signInRequired: false
	availableOnUIDS: false

Entry "EpiVis" (623) needs 
	availableOnOlympus: false
	signInRequired:false
	availableOnUIDS: false

Entry "EpiCaseMap" (622) needs 
	availableOnOlympus: false 
	signInRequired: true
	availableOnUIDS: false

Entry "FluSight" (624) needs 
	availableOnOlympus: false
	signInRequired: false
	availableOnUIDS: false

**Comment by jeffstazer** [comment]
For all Software these fields have been inserted if they do not currently exist:

availableOnOlympus
signInRequired
availableOnUIDS

each has been assigned true/false as indicated.
