### ISSUE TITLE
Disease Forecasters missing required fields in database json

### ISSUE THREAD

**Issue by JohnLevander** [midas-isg/digital-commons#203]
Entry "ILI-nearby" (632) needs 
	availableOnOlympus: false
	signInRequired: false
	availableOnUIDS: false

Entry "Dengue Forecasting Project" (629) needs 
	availableOnUIDS: false
	availableOnOlympus: false
	signInRequired: false

Entry "spaero: Software for Project AERO" (633) needs 
	availableOnUIDS: false
	availableOnOlympus: false
	signInRequired: false

Entry "FluOutlook" (630) needs 
	availableOnUIDS: false
	availableOnOlympus: false
	signInRequired: false

Entry "Columbia Prediction of Infectious Diseases" (627) needs 
	availableOnOlympus: false 
	signInRequired: false
	availableOnUIDS: false

Entry "FluSight: Seasonal Influenza Forecasting" (631) needs 
	availableOnOlympus: false
	signInRequired: false
	availableOnUIDS: false

Entry "Delphi" (628) needs 
	availableOnOlympus: false
	signInRequired: false
	availableOnUIDS: false

Entry "ZIKA Modeling" (634) needs 
	availableOnUIDS: false
	availableOnOlympus: false
	signInRequired: false

**Comment by jeffstazer** [comment]
For all Software these fields have been inserted if they do not currently exist:

availableOnOlympus
signInRequired
availableOnUIDS

each has been assigned true/false as indicated.
