### ISSUE TITLE
Data Format Converters missing required fields in database json

### ISSUE THREAD

**Issue by JohnLevander** [midas-isg/digital-commons#204]
Entry "spew2synthia" (613) needs 
	availableOnOlympus: true
	signInRequired: true
	availableOnUIDS: false

Entry "Omnivore" (612) needs 
	availableOnUIDS: false
	availableOnOlympus: false

**Comment by jeffstazer** [comment]
For all Software these fields have been inserted if they do not currently exist:

availableOnOlympus
signInRequired
availableOnUIDS

each has been assigned true/false as indicated.
