### ISSUE TITLE
Modeling Platforms missing required fields in database json

### ISSUE THREAD

**Issue by JohnLevander** [midas-isg/digital-commons#205]
Entry "Repast Simphony" (658) needs 
	availableOnUIDS: false
	availableOnOlympus: false
	signInRequired: false

Entry "NetLogo" (656) needs 
	availableOnOlympus: false 
	signInRequired: false
	availableOnUIDS: false

Entry "Repast for High Performance Computing" (657) needs 
	availableOnUIDS: false
	availableOnOlympus: false
	signInRequired: false

Entry "NetLogo" (655) needs 
	signInRequired: false
	availableOnUIDS: false

**Comment by jeffstazer** [comment]
For all Software these fields have been inserted if they do not currently exist:

availableOnOlympus
signInRequired
availableOnUIDS

each has been assigned true/false as indicated.
