### ISSUE TITLE
Disease Transmission Tree Estimators missing required fields in database json

### ISSUE THREAD

**Issue by JohnLevander** [midas-isg/digital-commons#206]
Entry "outbreaker" (653) needs 
	availableOnOlympus: 
	signInRequired: 
	availableOnUIDS:

**Comment by jeffstazer** [comment]
For all Software these fields have been inserted if they do not currently exist:

availableOnOlympus
signInRequired
availableOnUIDS

each has been assigned true/false as indicated.
