### ISSUE TITLE
Data Services missing required fields in database json

### ISSUE THREAD

**Issue by JohnLevander** [midas-isg/digital-commons#207]
Entry "Entrez Programming Utilities (E-utilities)" (615) needs 
	availableOnUIDS: false
	availableOnOlympus: false
	signInRequired: false

Entry "MedlinePlus Connect" (617) needs 
	availableOnUIDS: false
	availableOnOlympus: false
	signInRequired: false

Entry "RxNorm API" (619) needs 
	availableOnUIDS: false
	availableOnOlympus: false
	signInRequired: false

Entry "Project Tycho Repository - web app and API" (618) needs 
	availableOnUIDS: false
	availableOnOlympus: false
	signInRequired: false

Entry "Apollo LS database - web app and API" (614) needs 
	availableOnOlympus:  false
	signInRequired: false
	availableOnUIDS: false

Entry "Epi-Data API" (616) needs 
	availableOnUIDS: false
	availableOnOlympus: false
	signInRequired: false

**Comment by jeffstazer** [comment]
For all Software these fields have been inserted if they do not currently exist:

availableOnOlympus
signInRequired
availableOnUIDS

each has been assigned true/false as indicated.
