### ISSUE TITLE
Phylogenetic Tree Constructors missing required fields in database json

### ISSUE THREAD

**Issue by JohnLevander** [midas-isg/digital-commons#208]
Entry "PhyML" (664) needs 
	availableOnOlympus: false
	signInRequired: false
	availableOnUIDS: false

Entry "PHYLIP" (663) needs 
	availableOnUIDS: false
	availableOnOlympus: false
	signInRequired: false

**Comment by jeffstazer** [comment]
For all Software these fields have been inserted if they do not currently exist:

availableOnOlympus
signInRequired
availableOnUIDS

each has been assigned true/false as indicated.
