### ISSUE TITLE
Population Dynamics Model missing required fields in database json 

### ISSUE THREAD

**Issue by JohnLevander** [midas-isg/digital-commons#209]
Entry "Dynamic Mosquito Simulation Model (DyMSiM)" (665) needs 
	availableOnUIDS: false
	availableOnOlympus: false
	signInRequired: false

Entry "Skeeter Buster" (666) needs 
	availableOnUIDS: false
	availableOnOlympus: false
	signInRequired: false

**Comment by jeffstazer** [comment]
For all Software these fields have been inserted if they do not currently exist:

availableOnOlympus
signInRequired
availableOnUIDS

each has been assigned true/false as indicated.
