### ISSUE TITLE
Disease Transmission Model missing required fields in database json 

### ISSUE THREAD

**Issue by JohnLevander** [midas-isg/digital-commons#210]
Entry "Open Malaria" (638) needs 
	signInRequired: false
	availableOnUIDS: true

Entry "FluTE" (648) needs 
	availableOnOlympus: true
	signInRequired: false
	availableOnUIDS: true

Entry "Dengue transmission model" (646) needs 
	availableOnOlympus: true
	signInRequired: false
	availableOnUIDS: true

Entry "NAADSM" (636) needs 
	availableOnOlympus: false
	signInRequired: false
	availableOnUIDS: false

Entry "GLEAM" (651) needs 
	availableOnOlympus: false 
	signInRequired: false
	availableOnUIDS: false

Entry "Global Epidemic Simulator" (652) needs 
	availableOnOlympus: false
	signInRequired: false
	availableOnUIDS: false

Entry "Zika virus infections in childbearing women in the Americas" (644) needs 
	availableOnOlympus: false
	signInRequired: false
	availableOnUIDS: false

Entry "Open Malaria" (639) needs 
	availableOnOlympus: false
	signInRequired: false
	availableOnUIDS: false

Entry "Ebola transmission model" (647) needs 
	availableOnOlympus:  false
	signInRequired: false

Entry "FRED" (649) needs 
	availableOnOlympus: true 
	signInRequired: false
	availableOnUIDS: true

Entry "TranStat" (643) needs 
	availableOnOlympus: false
	signInRequired: false
	availableOnUIDS: false

Entry "Open Malaria" (637) needs 
	signInRequired: 
	availableOnUIDS: 

Entry "FRED Windows 64" (650) needs 
	availableOnOlympus: false
	signInRequired: false
	availableOnUIDS: false

Entry "Apollo FluTE" (635) needs 
	signInRequired: false

Entry "Pitt-Anthrax model" (641) needs 
	signInRequired: false

Entry "Pitt-SEIR model" (642) needs 
	signInRequired: false

Entry "pFRED" (640) needs 
	signInRequired: false

Entry "CLARA" (645) needs 
	signInRequired: false
	availableOnUIDS: false

**Comment by jeffstazer** [comment]
For all Software these fields have been inserted if they do not currently exist:

availableOnOlympus
signInRequired
availableOnUIDS

each has been assigned true/false as indicated.
