### ISSUE TITLE
Pathogen Evolution MOdels missing required fields in database json

### ISSUE THREAD

**Issue by JohnLevander** [midas-isg/digital-commons#211]
Disease Transmission Model missing required fields in database json

Entry "nextflu" (660) needs 
	availableOnOlympus: false
	signInRequired: false
	availableOnUIDS: false

Entry "nextstrain organization" (661) needs 
	availableOnOlympus: false
	signInRequired: false
	availableOnUIDS: false

Entry "HyPhy" (659) needs 
	availableOnUIDS: false
	signInRequired: false

Entry "SEEDY" (662) needs 
	availableOnUIDS: false
	availableOnOlympus: false
	signInRequired: false

**Comment by jeffstazer** [comment]
For all Software these fields have been inserted if they do not currently exist:

availableOnOlympus
signInRequired
availableOnUIDS

each has been assigned true/false as indicated.
