### ISSUE TITLE
Should entry 1022 (Communicable Diseases Quarterly Reports of Syrian Ministry of Health) be a DatasetWithOrganization?

### ISSUE THREAD

**Issue by JohnLevander** [midas-isg/digital-commons#220]
I see {"name":{"type":"organization","description":"Early Warning Alert and Response System (EWARS), Syrian Ministry of Health"}} in the creators section...

**Comment by jeffstazer** [comment]
Anything with this schema...{"name":{"type":"organization","description"

should be DatasetWithOrganization.  postgres script is written to convert them, but has not been executed nor tested on the TEST database yet.

**Comment by jeffstazer** [comment]
please see... https://github.com/midas-isg/digital-commons/issues/198

**Comment by jeffstazer** [comment]
All datasets with this schema

{"name":{"type":"organization","description"

have been converted to DatasetWithOrganization
