### ISSUE TITLE
dats.xsd "anyURI" data type

### ISSUE THREAD

**Issue by jeffstazer** [midas-isg/digital-commons#237]
Access (LandingPage and accessURL), CategoryIRI and IdentifierSource have a type of "anyURI" in dats.   Should these have a validation?

Looking at the data in the database...
IdentiferSource -- is mostly just text strings (ex. Geonames, ISG, ISO 3166, URL, FAIRsharing)

categoryIRI - only has 3 entries populated -- 2 are empty strings, the other ("http://purl.obolibrary.org/obo/FBcv_0000667")

landingPage -- all contain http except one empty string

accessURL -- all contain http

I created validations for landingPage and accessURL

Do we need to clean the data for identifierSource and categoryIRI?

**Comment by JohnLevander** [comment]
I think the identifierSource should have a protocol.  Not necessarily HTTP, but something.  I'm not sure we can "clean it" yet.

For category IRI I'd say just delete the blank entries.
