### ISSUE TITLE
DataStandard->license specifies 2 identifer elements but they are not wrapped in an Identifier

### ISSUE THREAD

**Issue by jeffstazer** [midas-isg/digital-commons#238]
DataStandard->license specifies 2 identifer elements but they are not wrapped in an Identifier

    <complexType name="License">
        <sequence>
            <element name="identifier" type="tns:nonZeroLengthString"></element>
            <element name="identifierSource" type="anyURI" minOccurs="0"/>
            <element name="version" type="tns:nonZeroLengthString" minOccurs="0"/>

        </sequence>
    </complexType>

    <complexType name="Identifier">
        <sequence>
            <element name="identifier" type="tns:nonZeroLengthString" minOccurs="1" maxOccurs="1"></element>
            <element name="identifierSource" type="tns:nonZeroLengthString" minOccurs="0" maxOccurs="1"></element>
        </sequence>
    </complexType>

**Comment by jeffstazer** [comment]
identifier has been updated to be of type Identifier, but identifierSource should be removed...

    <complexType name="License">
        <sequence>
            <element name="name" type="tns:nonZeroLengthString" minOccurs="1" maxOccurs="1"/>
            <element name="identifier" type="tns:Identifier"></element>
            <element name="identifierSource" type="anyURI" minOccurs="0"/>
            <element name="version" type="tns:nonZeroLengthString" minOccurs="0"/>
            <element name="creators" type="tns:PersonComprisedEntity" minOccurs="0" maxOccurs="unbounded"/>
        </sequence>
    </complexType>

**Comment by JohnLevander** [comment]
Fixed in the next commit.
