### ISSUE TITLE
DataStandard->type is a required annotation.  Which annotation elements should be required?

### ISSUE THREAD

**Issue by jeffstazer** [midas-isg/digital-commons#239]
Throughout we are treating Annotation to have a minimum of 0.  This matches the [annotation_schema](https://github.com/biocaddie/WG3-MetadataSpecifications/blob/master/json-schemas/annotation_schema.json).  In the dats.xsd, it's not specified...

    <complexType name="Annotation">
        <sequence>
            <element name="value" type="tns:nonZeroLengthString"></element>
            <element name="valueIRI" type="tns:nonZeroLengthString"></element>
        </sequence>
    </complexType>

In ConformsTo which is of type DataStandard, there is an element "type" which is of type "Annotation" and has a required minimum of 1.  This matches the [data_standard_schema](https://github.com/biocaddie/WG3-MetadataSpecifications/blob/master/json-schemas/data_standard_schema.json).

    <complexType name="DataStandard">
        <sequence>

            <element name="type" type="tns:Annotation" minOccurs="1" maxOccurs="1"/>

        </sequence>
    </complexType>

Should we require both value and valueIRI for the DataStandard "type"?

**Comment by JohnLevander** [comment]
Not being specified in .xsd means: minOccurs=1 maxOccurs=1.  To match the DATS spec, I'll make the value and valueIRI optional.
