### ISSUE TITLE
IdentifierSource required when Identifier is populated

### ISSUE THREAD

**Issue by jeffstazer** [midas-isg/digital-commons#240]
The description for IdentiferSource indicates it is required when the Identifier is provided.

[Description:](https://github.com/biocaddie/WG3-MetadataSpecifications/blob/master/json-schemas/identifier_info_schema.json)
(The identifier source represents information about the organisation/namespace responsible for minting the identifiers. It must be provided if the identifier is provided.)

**Comment by JohnLevander** [comment]
Fixed in the next commit.
