### ISSUE TITLE
Geometry has no existing data in database

### ISSUE THREAD

**Issue by jeffstazer** [midas-isg/digital-commons#245]
the dats.xsd type Place specifies and element geometry.  These definitions are indicated below.  There are no instances of geometry in the current data.  Doesn't hurt anything to be included, but wanted to double check it should be included in the dats.xsd.

    <complexType name="Place">
        <sequence>
            <element name="identifier" type="tns:Identifier" minOccurs="0"/>
            <element name="name" type="tns:nonZeroLengthString" minOccurs="1" maxOccurs="1"></element>
            <element name="description" type="tns:nonZeroLengthString" minOccurs="0" maxOccurs="1"></element>
            <element name="postalAddress" type="tns:nonZeroLengthString" minOccurs="0" maxOccurs="1"/>
            <element name="geometry" type="tns:Geometry" minOccurs="0" maxOccurs="1"/>
            <element name="coordinates" type="tns:nonZeroLengthString"/>
        </sequence>
    </complexType>

    <simpleType name="Geometry">
        <restriction base="string">
            <enumeration value="POINT"></enumeration>
            <enumeration value="MULTIPOINT"></enumeration>
            <enumeration value="LINESTRING"></enumeration>
            <enumeration value="MULTILINESTRING"></enumeration>
            <enumeration value="POLYGON"></enumeration>
            <enumeration value="MULTIPOLYGON"></enumeration>
            <enumeration value="GEOMETRYCOLLECTION"></enumeration>
        </restriction>
    </simpleType>

**Comment by JohnLevander** [comment]
Yes I think we can leave it there for now.
