### ISSUE TITLE
Entry 731 is not allowed to have "description" in the isAbout

### ISSUE THREAD

**Issue by JohnLevander** [midas-isg/digital-commons#247]
Can you please delete the "description" from the isAbout in Entry 731?

"isAbout":[  
      {  
         "name":"HIV/AIDS incidences in Russia",
         **"description":"Data about incidences of HIV/AIDS in Russia by region from 1994 to 2012 year in HTML format. Spatial coverage is country, and spatial resolution is region. Temporal coverage is 1994-2012, and temporal resolution is yearly. Open access"**
      }
   ],

**Comment by jeffstazer** [comment]
description has been removed from the isAbout for entry 731.
