### ISSUE TITLE
Validations (existing data) - missing Creator

### ISSUE THREAD

**Issue by jeffstazer** [midas-isg/digital-commons#250]
There is no creator specified for [entry_id=86](http://localhost:8080/digital-commons/detailed-view/?id=86).

Just need to know what person or organization to insert for this record.

**Comment by JohnLevander** [comment]
"creators": [
{
"name": "RODS Laboratory, University of Pittsburgh"
}
],

**Comment by jeffstazer** [comment]
This record has been updated.
