### ISSUE TITLE
Validations (existing data) - Missing required Type data

### ISSUE THREAD

**Issue by jeffstazer** [midas-isg/digital-commons#251]
Type requires at least one of Types-Information, Types->Method or Types->Platform to be specified.  Each of these are of type Annotation (value, valueIRI).

This information does not exist for these entry_ids: 1151, 1067, 1155, 1169, 1149, 1148
These 6 are all data.gov imports.  All but 1067 are Location data.  And those 5 are the only ones specified as Location data.

For 1067, revision id = 1 had this in Types: [{"information": {"value": "case series", "valueIRI": "http://purl.obolibrary.org/obo/APOLLO_SV_00000559"}}].  Probably want to insert this back into 1067.

For the other 5, we need to specify something for at least one Annotation.

**Comment by JohnLevander** [comment]
Notes for later use:

1151 is Air Pollution Data
1067 is Number of cases of TB by state, etc
1155 is locations on where to get vaccinated
1169 demographics by zipcode
1149 is locations of vaccination clinics
1148 is locations of vaccination clinics 

1067 really isn't a case series..it's more of a Case Count, and we need to find a vocab item to report it.

**Comment by jeffstazer** [comment]
These records have been updated to include the indicated data above.
