### ISSUE TITLE
FAIR Metrics (FAIRness) - URL is expected if License is populated

### ISSUE THREAD

**Issue by jeffstazer** [midas-isg/digital-commons#258]
If a license is specified FAIR metrics expects a URL specified.  For Project Tycho, this is specified in the Identifier field: (Tycho are: {"identifier": "https://creativecommons.org/licenses/by-nc-sa/4.0/", "identifierSource": "URL"}).

path: content->'entry'->'licenses'->0
For those with License populated here are the contents and count:

contents and count
{"name": ""}	7
{"name": "Apache License 2.0"}	3
{"name": "CC BY 3.0 US"}	5
{"name": "GNU General Public License"}	1
{"name": "https://www.tycho.pitt.edu/legal/license_agreement.html"}	2
{"name": "No License Specified."}	5

For the empty string and "No License Specified.", I suggest we remove license for these 12 entries.

To match the Tycho format, we need to specify an Identifier and IdentifierSource for the other 11.  So, what should those be?

**Comment by jeffstazer** [comment]
Below are what I believe we should set the identifiers to...
identifierSource will be set to URL

Apache:
[https://www.apache.org/licenses/LICENSE-2.0](https://www.apache.org/licenses/LICENSE-2.0)

CC BY 3.0 US
[http://creativecommons.org/licenses/by/3.0/us/](http://creativecommons.org/licenses/by/3.0/us/)

GNU General Public License
[https://www.gnu.org/licenses/gpl-3.0.en.html](https://www.gnu.org/licenses/gpl-3.0.en.html)

Tycho
[https://www.tycho.pitt.edu/license/](https://www.tycho.pitt.edu/license/)

**Comment by JohnLevander** [comment]
Everything looks good, only thing I don't agree with is the Tycho license link in comment 2, just point to the cc by 40 (the first link mentioned in the issue).

**Comment by jeffstazer** [comment]
License has been removed for those 12 records with empty strings.

The other 4 have been updated.  the first 3 as indicated above and Tycho as John specified.
