### ISSUE TITLE
FAIR Metrics (FAIRness) - Identifiers contain spaces

### ISSUE THREAD

**Issue by jeffstazer** [midas-isg/digital-commons#259]
There are 7 identifiers in the database which contain a space.

The identifiers are:
"Brazil Ministry of Health public disease surveillance website"
"Singapore Routine Surveillance"
"MMWR morbidity and mortality tables"
"Federal Center against HIV/AIDS of Russia"
"CDCEpi Zika Github"
"CDC WONDER US cause of death 1968-2015"
"CDC WONDER US cause of death 1995-2015"

These identifiers do not play well with FAIR Metrics.  Should we replace the spaces with underscores?  Do something else?

**Comment by JohnLevander** [comment]
Maybe use the URLs to these sites for the identifiers?  The websites with data (1, 2, 4) have low importance (url will probably be fine).

I feel like 3, 6, 7 probably have entires from Data.gov (so make sure we didn't duplicate any entires).

5 is important, but using the URL should be fine.

**Comment by jeffstazer** [comment]
The URL has been set as the identifier for these 7 records.  These new identifiers have been checked against the dataset and are unique.
