### ISSUE TITLE
FAIR Metrics (FAIRness) - Tycho identifiers for Distributions->ConformsTo need updated

### ISSUE THREAD

**Issue by jeffstazer** [midas-isg/digital-commons#260]
Tycho identifiers need converted to a URL to comply with FAIR metrics.

path: content->'entry'->'distributions'->0->'conformsTo'->0->'identifier'
contains: {"identifier": "bsg-s000718", "identifierSource": "FAIRsharing"}

identifier should be updated to: https://fairsharing.org/bsg-s000718

**Comment by JohnLevander** [comment]
Approved.

**Comment by jeffstazer** [comment]
The Tycho identifiers have been updated.
