### ISSUE TITLE
FAIR Metrics (FAIRness) - Entries containing doi/zenodo/ptycho as identifier need identifierSource updated/created

### ISSUE THREAD

**Issue by jeffstazer** [midas-isg/digital-commons#261]
We have 527 entries which have an identiifier containing doi, or zenodo, or ptycho.  The identifierSource for these are "Project Tycho" or "zenodo" or the identifierSource is missing.

The identifierSource should be 'https://fairsharing.org/bsg-s001182' for all these records.

**Comment by JohnLevander** [comment]
That's fine.

**Comment by jeffstazer** [comment]
identifierSource has been updated for these 527 records.
