### ISSUE TITLE
FAIR Metrics (FAIRness) - IdentifierSource missing for main Identifier

### ISSUE THREAD

**Issue by jeffstazer** [midas-isg/digital-commons#262]
There are 34 records not covered by [Issue 261](https://github.com/midas-isg/digital-commons/issues/261).

None of these 34 records have an identifierSource specified.  One needs to be created for them and be a URL to comply with FAIR metrics.

These 34 records can be found in the tab "MDC create IDSource" of the [FAIR Metrics google sheet](https://docs.google.com/spreadsheets/d/1l4QVdhvLi2ilJoBQ9-UM0ncN3fF-imBu0tNgnxrJMTw/edit?ts=5b61c74f#gid=359228191).

**Comment by jeffstazer** [comment]
Based upon the 380 records with an identifierSource specified and where the identifier contains "MIDAS-ISG" as part of the identifier, i believe the identifierSource should be set to "MIDAS-ISG" for the 33 records where identifierSource is missing.

this leaves us with one more record to deal with.  It's identifier is...
{"identifier": "http://www.nature.com/articles/nmicrobiol2016126"}
There are 2 other records with "http:" as part of the identifier but both of these are epimodels and the identifierSource is "MIDAS Informatics Services Group".  What should the identifierSource for this record be?

**Comment by JohnLevander** [comment]
If the identifier is a URL (and can't be more specific (e.g. DOI)), the source should https://fairsharing.org/bsg-s001186/

If we can't just put the identifier source as "MIDAS-ISG," for entires beginning with "MIDAS-ISG" then the next best thing would be to put http://www.epimodels.org/digital-commons/

**Comment by jeffstazer** [comment]
For all 411 records where the identifier contains "MIDAS-ISG", the identifierSource has been set to "http://www.epimodels.org/digital-commons/".

For the record where the identifier is "http://www.nature.com/articles/nmicrobiol2016126", the identifierSource has been set to "https://fairsharing.org/bsg-s001186/".
