### ISSUE TITLE
Default Identifiers for objects to http if possible

### ISSUE THREAD

**Issue by JohnLevander** [midas-isg/digital-commons#270]
For example the identifier for the "Pitt-Anthrax model" is: https://zenodo.org/record/439078.

We want that identifier to be changed to http://zenodo.org/record/439078.

**Comment by jeffstazer** [comment]
These Identifiers have been updated to http.

"King County onsite employee flu vaccination clinics" has been hidden.  All links in this entry are no longer findable (404 Client Error (Not Found)).
