### ISSUE TITLE
Eliminate use of NA, or N/A to describe dataInputFormats and dataOutputFormats

### ISSUE THREAD

**Issue by JohnLevander** [midas-isg/digital-commons#273]
We use NA to either mean "not applicable" or "not available" this is not precise enough.

When we use NA to mean "not applicable" (as in there is no value for this field) we should say "None."  For example if there is software that does not accept an input, we should set the value of this field to be "None."

When we use NA to mean "not available" that means we don't know the input type for some reason.  We should replace this usage of NA with "Syntax Not Available."

**Comment by jeffstazer** [comment]
The data shows ZERO entries with NA or N/A for dataInputFormats.
The data shows THREE entries with N/A for dataOutputFormats; none contain NA.

[Epi-Data API](http://betaweb.rods.pitt.edu/digital-commons-dev/detailed-view/?id=616)
[VirFinder](http://betaweb.rods.pitt.edu/digital-commons-dev/detailed-view/?id=1171)
[VirHostMatcher](http://betaweb.rods.pitt.edu/digital-commons-dev/detailed-view/?id=1172)

**Comment by jeffstazer** [comment]
We are transferring the contents of dataOutputFormats into outputs->dataFormats [(Update Software XSD to increase clarity of input/output data formats).](https://github.com/midas-isg/digital-commons/issues/272)  dataOutputFormats containing N/A were not transferred.  As we convert to using outputs instead of dataOutputFormats the contents of these 3 with N/A will disappear.

**Comment by jeffstazer** [comment]
If no data has been entered (meaning dataInputFormats or dataOutputFormats doens't exist in the json, in the commons.js file at line 680 we were inserting 'N/A'.  Changed this to 'System Not Available.'.

So I now believe the 3 entry_id's above should have 'None'.

**Comment by jeffstazer** [comment]
Updated 

Epi-Data API
VirFinder
VirHostMatcher

to have None as an Output
