### ISSUE TITLE
Hide the Galapagos entry.  It's not maintained anymore.

### ISSUE THREAD

**Issue by JohnLevander** [midas-isg/digital-commons#276]

**Comment by jeffstazer** [comment]
Should we hide the Data Visualizer as well as the Data Formats?

Data Visualizer
[Galapagos - v1.0](http://betaweb.rods.pitt.edu/digital-commons-dev/detailed-view/?id=625)

Data Formats
[Galapagos CSV - v1](http://betaweb.rods.pitt.edu/digital-commons-dev/detailed-view/?id=591)
[Galapagos CSV - v2](http://betaweb.rods.pitt.edu/digital-commons-dev/detailed-view/?id=590)

The following have references to Galapagos in their "Formats for data output:".
[Pitt-SEIR model](http://betaweb.rods.pitt.edu/digital-commons-dev/detailed-view/?id=642)
[pFRED](http://betaweb.rods.pitt.edu/digital-commons-dev/detailed-view/?id=640)
[Apollo FluTE](http://betaweb.rods.pitt.edu/digital-commons-dev/detailed-view/?id=635)
[Pitt-Anthrax model](http://betaweb.rods.pitt.edu/digital-commons-dev/detailed-view/?id=641)
[Ebola transmission model](http://betaweb.rods.pitt.edu/digital-commons-dev/detailed-view/?id=647)

Should we edit Formats for data output for those above?

**Comment by jeffstazer** [comment]
Galapagos has been removed.
