### ISSUE TITLE
JSON attribute-value mismatch in data-formats-dats-json files

### ISSUE THREAD

**Issue by dillerm** [midas-isg/digital-commons#62]
I've only noticed this in two of the files in the [data-formats-dats-json folder](https://github.com/midas-isg/digital-commons/tree/master/src/main/webapp/resources/data-formats-dats-json): 'Apollo Case Series.json' and 'Apollo Epidemic.json'.

In the aforementioned files, the 'name' attribute in the 'licenses' array has the value "case series" and "epidemic," respectively. In addition, in both files, the 'valueIRI' attribute in the 'type' object has "Michael Wagner, John Levander, Nicholas Millet, William Hogan" as its value. 

See below for visualizations of each:

**licenses**
```
"licenses": [
        {
            "name": "\"epidemic\""
        }
    ],
```

**valueIRI**
```
"type": {
        "value": "http://purl.obolibrary.org/obo/APOLLO_SV_00000298",
        "valueIRI": "Michael Wagner, John Levander, Nicholas Millett, William Hogan"
```

**Comment by adamdarr** [comment]
This was an issue with a parser I wrote. The files should be updated and the problem fixed. Thanks!
