### ISSUE TITLE
Data format identifiers are mismatched between software JSON and data format DATS

### ISSUE THREAD

**Issue by hoganwr** [midas-isg/digital-commons#64]
An incomplete list:

DATS:  MIDAS-ISG:spew-us-format-v1.2.0
software JSON: MIDAS-ISG:spew-us-v1.2.0

DATS:  IETF:rfc7946
software JSON: IETF:GeoJSON-rfc7946

DATS: MIDAS-ISG:synthia-us-v2010
software JSON: MIDAS-ISG:synthia-us-format-v2010

**Comment by adamdarr** [comment]
Fixed. Thanks!
