### ISSUE TITLE
License names in the following DATS folders are replaced with the actual wording of the license itself: case-series-, chikungunya-, ebola-, infectious-disease-,  and zika-dats-json.

### ISSUE THREAD

**Issue by dillerm** [midas-isg/digital-commons#97]

**Comment by hoganwr** [comment]
For everything you put on Zenodo, the license is CC BY 4.0.  Ideally, the license attribute in the DATS files would be the following string "CC BY 4.0".  

This includes all the SPEW and Ebola DATS.
